---
title: "Second try with fixed MSTRG gene names"
output: html_notebook
---

```{r}
# Install apeglm package
BiocManager::install(c("apeglm"))
```

```{r}
library(tidyverse)
library(here)
library(DESeq2)
library(dplyr)
```

```{r}
rm(list = ls()) # removing everything from the R environment because it was all wrong
```

```{r}
gene_counts <- read.csv(here("data", "gene_count_matrix_fixed.csv"))
transcript_counts <- read.csv(here("data", "transcript_count_matrix_fixed.csv"))
colData <- read.csv(here("data", "sample_info.csv"))
```

```{r}
# Are the row names in colData matching the column names in gene_counts?
all(rownames(colData) %in% colnames(gene_counts)) # FALSE

gene_counts <- column_to_rownames(gene_counts, var = "gene_id")
gene_counts

all(rownames(colData) %in% colnames(gene_counts)) # still FALSE

colData <- column_to_rownames(colData, var = "sample_id")
colData

all(rownames(colData) %in% colnames(gene_counts)) #TRUE

# Are the row names in colData and column names in gene_counts in the same order?
all(rownames(colData) == colnames(gene_counts)) #TRUE
```

```{r}
# Create a DESeqDataSet from count matrix and labels
dds <- DESeqDataSetFromMatrix(countData = gene_counts, colData = colData, design = ~ treatment)

dds

# Before running DESeq2 analysis we can do some pre-filtering and remove rows that have low gene counts across all the samples (recommended step)
keep <- rowSums(counts(dds)) >= 10

dds <- dds[keep,]
dds

# Set the factor level
# Use control as a reference level to compare vs the treated
dds$treatment <- relevel(dds$treatment, ref = "control")

# Collapse technical replicates
?collapseReplicates # not sure if needed
collapseReplicates(gene_counts, groupby = gene_id)

# Checking if there are any technical replicates
duplicated(gene_counts)
# Yes there are. How many technical replicates are there all together?
# When running the command right after importing the data (before it is processed anyhow), it's all FALSE. So there are no technical replicates. Pretty sure but double check
duplicated(gene_counts) %>%
  count(value = TRUE)

?duplicated
?base::duplicated

collapseReplicates()
```

```{r}
# Run DESeq2

dds <- DESeq(dds)
res <- results(dds)
res

# Specify the coefficient/contrast we want to build a results table for
res <- results(dds, name="condition_treatment_vs_control")
res <- results(dds, contrast=c("condition","treatment","control"))
res

# Log fold change shrinkage for visualization and ranking
resultsNames(dds)
resLFC <- lfcShrink(dds, coef = "condition_treatment_vs_control", type="apeglm")

# using 'apeglm' for LFC shrinkage. If used in published research, please cite:
# Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for sequence count data: removing the noise and preserving large differences. Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895

resLFC
```

```{r}
# p-values and adjusted p-values
resOrdered <- res[order(res$padj),]
head(resOrdered) 

summary(res)
head(results(dds, tidy = TRUE))

# How many adjusted p-values were less than 0.1?
sum(res$padj < 0.1, na.rm=TRUE)

res05 <- results(dds, alpha=0.05)
summary(res05)

# How many adjusted p-values were less than 0.05?
sum(res05$padj < 0.05, na.rm = TRUE)
```

```{r}
# Independent hypothesis weighting
# is it needed?
install.packages("IHW") # package not available for this version of R
library("IHW")
```

```{r}
#Exploring and exporting results
# MA-plot

plotMA(res, ylim=c(-2,2))
plotMA(resLFC, ylim=c(-2,2))

# Plot counts
plotCounts(dds, gene = which.min(res$padj), intgroup = "treatment")
# plots the count for the gene which had the smallest p value
# what is a p value and what does a low p value mean?

# In statistical hypothesis testing, the p-value or probability value is the probability of obtaining test results at least as extreme as the results actually observed during the test, assuming that the null hypothesis is correct (Wikipedia). A low p-value is evidence in favor of the alternative hypothesis - it allows you to reject the null hypothesis (OmniCalculator).
# Does this mean the lowest p value is the most significant DE?

# TNFAIP2 is a cell migration-promoting protein and its expression predicts distant metastasis.
```

```{r}
# Data transformations and visualization
# Count data transformations

vsd <- vst(dds, blind = FALSE)
rld <- rlog(dds, blind = FALSE)
head(assay(vsd), 3)

# The point of these two transformations above, is to remove the dependence of the variance on the mean

ntd <- normTransform(dds)
```

```{r}
library("pheatmap")
select <- order(rowMeans(counts(dds, normalized = TRUE)), decreasing = TRUE)[1:20]
df <- as.data.frame(colData)

rownames(df) <- colnames(ntd)
colData

pheatmap(assay(ntd)[select,], cluster_rows = FALSE, show_rownames = FALSE, cluster_cols = FALSE, annotation_col = df)
```












