---
title: "Differential gene expression analysis using DESeq2"
output: html_notebook
---

```{r}
library("tidyverse")
library("here")
library("DESeq2")
```

```{r}
gene_counts
colData

# Are the row names in colData matching the column names in gene_counts?
all(rownames(colData) %in% colnames(gene_counts)) # FALSE

gene_counts <- column_to_rownames(gene_counts, var = "gene_id")
gene_counts

all(rownames(colData) %in% colnames(gene_counts)) # still FALSE

colData <- column_to_rownames(colData, var = "sample_id")
colData

all(rownames(colData) %in% colnames(gene_counts)) #TRUE

# Are the row names in colData and column names in gene_counts in the same order?
all(rownames(colData) == colnames(gene_counts)) #TRUE
```

```{r}
# Create a DESeqDataSet from count matrix and labels
dds <- DESeqDataSetFromMatrix(countData = gene_counts, colData = colData, design = ~ treatment)

dds

# Before running DESeq2 analysis we can do some pre-filtering and remove rows that have low gene counts across all the samples (recommended step)
dds2 <- rowSums(counts(dds)) >= 10

dds <- dds[dds2,]
dds

# Set the factor level
# Use control as a reference level to compare vs the treated
dds$treatment <- relevel(dds$treatment, ref = "control")
```

```{r}
# Run DESeq

dds <- DESeq(dds)
res <- results(dds)

res
# baseMean: average of the normalized count taken over all samples
# log2FoldChange: fold change of genes in the treated condition when compared with the control (positive = upregulated, negative = downregulated)
## all fold changes are results for the "treated" because the treated is compared to the control
# lfcSE: standard error estimates of the log2FoldChange
# stat: 
# pvalue: 
# padj: corrected p value for multiple testing

summary(res)

res0.01 <- results(dds, alpha = 0.01)
summary(res0.01)

# MA plot
plotMA(res)

#

```




