---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(dplyr)
```

```{r}
# sig_res_ids exploration
sig_res_ids$padj <- as.character(sig_res_ids$padj)
sig_res_ids$log2FoldChange <- as.character(sig_res_ids$log2FoldChange)

sig_res_ids1 <- sig_res_ids %>%
  dplyr::select(gene, log2FoldChange, padj, symbol, chr, biotype, description) %>%
  arrange(desc(log2FoldChange))

write.csv(sig_res_ids1, here("output/DE/all_sig_res.csv"))
```

```{r}
# Biotypes
ggplot(sig_res_ids, aes(x = biotype, fill = chr)) + geom_dotplot(binwidth = 0.2) + theme(axis.text.x = element_text(angle = 90)) + theme(
  panel.background = element_rect(fill = "white", colour = "grey50"), 
  panel.border = element_rect(linetype = "solid", fill = NA, colour = "grey50"),
  axis.ticks = element_line(colour = "grey50"))

ggplot(res_ids, aes(x = biotype, fill = chr)) + geom_dotplot(binwidth = 0.2) + theme(axis.text.x = element_text(angle = 90)) + theme(
  panel.background = element_rect(fill = "white", colour = "grey50"), 
  panel.border = element_rect(linetype = "solid", fill = NA, colour = "grey50"),
  axis.ticks = element_line(colour = "grey50"))

ggsave(here("output/biotypes.png"), width = 10, height = 7)

sig_res_ids1 %>%
  arrange(padj)

sig_res_ids1 %>%
  dplyr::filter(biotype != "protein_coding") %>%
  arrange(padj)

sig_res_ids1 %>%
  dplyr::filter(biotype == "processed_pseudogene") #5

sig_res_ids1 %>%
  dplyr::filter(biotype == "transcribed_processed_pseudogene") #2

sig_res_ids1 %>%
  dplyr::filter(biotype == "transcribed_unprocessed_pseudogene") #5

sig_res_ids1 %>%
  dplyr::filter(biotype == "unprocessed_pseudogene") #3

sig_res_ids1 %>%
  dplyr::filter(biotype == "lncRNA")
```

```{r}
# Artifacts/novel proteins
sig_res_ids %>%
  dplyr::filter(biotype == "artifact")
```

```{r}
# 43 lncRNAs 
lncRNAs <- sig_res_ids1 %>%
  dplyr::filter(biotype == "lncRNA") %>%
  arrange(desc(log2FoldChange))

write.csv(lncRNAs, here("output/DE/sig_lncRNAs.csv"))
```

```{r}
# 1 TEC (To be Experimentally Confirmed) - uncategorised

sig_res_ids1 %>%
  dplyr::filter(biotype == "TEC")

# ENSG00000279692 -> no disorders and no publications
# ENSG00000279089 -> mentioned in only one publications (https://rucore.libraries.rutgers.edu/rutgers-lib/61905/PDF/1/play/) as a gene rescued only by SOX9 WT 

plotCounts(dds, gene="ENSG00000279692", intgroup = "treatment", main = "TEC") 
```

```{r}
# 1 small nuclear RNA

sig_res_ids1 %>%
  dplyr::filter(biotype == "misc_RNA")

plotCounts(dds, gene="ENSG00000202198", intgroup = "treatment", main = "7SK") # insignificant due to a difference between control sample values?
```

