---
title: "R Notebook"
output: html_notebook
---

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("biomaRt")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Glimma")
```


```{r}
library(tidyverse)
library(ggplot2)
library(here)
library(DESeq2)
library(dplyr)
# library(biomaRt) # requires dplyr >= 1.1.0v
library(Glimma)
```

```{r}
#Exploring and exporting results
# MA-plot

plotMA(res, ylim=c(-2,2))
plotMA(resLFC, ylim=c(-2,2))

# genes with high log-fold change and high mean of normalized counts are interesting candidates to look further into
## why?
# because they are likely to represent genes that are significantly differentially expressed and biologically relevant (ChatGPT)
# -> high fold change indicates a large difference in expression levels between the two conditions being compared
# -> high normalized mean count indicates that the gene is expressed at a relatively high level in the samples being compared

# Interactive Glimma MD-plot
status <- as.numeric(res$padj < .05)
anno <- data.frame(GeneID=rownames(res))
glMDPlot(res, status=status, counts=counts(dds,normalized=TRUE),
         groups=dds$treatment, transform=FALSE,
         samples=colnames(dds), anno=anno, folder="../output/interactive_MD", launch=FALSE)
```

```{r}
# countPlots

plotCounts(dds, gene = which.min(res$padj), intgroup = "treatment")
# plots the count for the gene which had the smallest p value

# Customized plotting
d <- plotCounts(dds, gene=which.min(res$padj), intgroup="treatment", 
                returnData=TRUE)
ggplot(d, aes(x=treatment, y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0), shape=21) +
  theme_bw() + 
  ggtitle("ENSG00000185215|TNFAIP2") +
  xlab("Treatment") + ylab("Normalized count") +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid = element_line(colour = "white")) +
  scale_x_discrete(labels = c("Control", "mCD40L")) +
  scale_y_continuous(trans = "log10")

head(resOrdered, n = 9)
par(mfrow=c(3,3))
plotCounts(dds, gene="MSTRG.7481|ENSG00000185215|TNFAIP2", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.12001|ENSG00000090339|ICAM1", intgroup = "treatment")
plotCounts(dds, gene="ENSG00000056558|TRAF1", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.19332|ENSG00000125347|IRF1", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.3184|ENSG00000077150|NFKB2", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.6860|ENSG00000100906|NFKBIA", intgroup = "treatment")
plotCounts(dds, gene="ENSG00000118503|TNFAIP3", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.4048|ENSG00000110047|EHD1", intgroup = "treatment")
plotCounts(dds, gene="MSTRG.19549|ENSG00000145901|TNIP1", intgroup = "treatment")
```


```{r}
results_table <- rownames_to_column(results_table, var = "gene_id")

results_table %>%
  filter(gene_id %in% c("MSTRG.7481|ENSG00000185215|TNFAIP2", 
                        "MSTRG.12001|ENSG00000090339|ICAM1",
                        "ENSG00000056558|TRAF1",
                        "MSTRG.19332|ENSG00000125347|IRF1",
                        "MSTRG.3184|ENSG00000077150|NFKB2",
                        "MSTRG.6860|ENSG00000100906|NFKBIA",
                        "ENSG00000118503|TNFAIP3",
                        "MSTRG.4048|ENSG00000110047|EHD1",
                        "MSTRG.19549|ENSG00000145901|TNIP1",
                        "MSTRG.20196|ENSG00000168394|TAP1"
                        ))
```


